import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import SiteNavbar from '@/components/SiteNavbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<SiteNavbar />
				<div className="app-wrapper max-w-5xl m-auto pt-6">{children}</div>
			</body>
		</html>
	);
}
